#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
HOST = data.get("host")
app_config = {
    "URL": "https://"+HOST,
}
agent.write_envfile("app.env", app_config)

# just before starting systemd unit
#agent.dump_env()
