#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)


SECRET_KEY = secrets.token_hex(32)
UTILS_SECRET = secrets.token_hex(32)

app_env = {
    'SECRET_KEY': SECRET_KEY,
    'UTILS_SECRET': UTILS_SECRET,
    'DATABASE_URL': DATABASE_URL,
    'REDIS_URL': REDIS_URL,
}

agent.write_envfile("secrets.env", app_env)

# just before starting systemd unit
# agent.dump_env()

