#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

PASSWORD = secrets.token_urlsafe(16)

# Configure Database
POSTGRES_DB = data.get('POSTGRES_DB', 'outline')
POSTGRES_USER = data.get('POSTGRES_USER', 'outline')
POSTGRES_PASSWORD = data.get('POSTGRES_PASSWORD', PASSWORD)
POSTGRES_HOST = data.get('POSTGRES_HOST', 'postgresql-app')
POSTGRES_PORT = data.get('POSTGRES_PORT', 5432)

postgres = {
    'POSTGRES_DB': POSTGRES_DB,
    'POSTGRES_USER': POSTGRES_USER,
    'POSTGRES_PASSWORD': POSTGRES_PASSWORD,
    'POSTGRES_HOST': POSTGRES_HOST,
    'POSTGRES_PORT': POSTGRES_PORT,
}
agent.write_envfile("database.env", postgres)

SECRET_KEY = secrets.token_hex(32)
UTILS_SECRET = secrets.token_hex(32)
DATABASE_URL = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
REDIS_URL="redis://redis-app:6379"

app_env = {
    'SECRET_KEY': SECRET_KEY,
    'UTILS_SECRET': UTILS_SECRET,
    'DATABASE_URL': DATABASE_URL,
    'REDIS_URL': REDIS_URL,
}

agent.write_envfile("secrets.env", app_env)

# just before starting systemd unit
# agent.dump_env()

